2020-10-23 02:28:26,633 ERROR: Exception on /protected [GET] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/mmaitland300/flask/projectmatt/app/main/views.py", line 341, in lehigh
    return render_template('mcshea/welcome.html')
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mmaitland300/flask/projectmatt/app/templates/mcshea/welcome.html", line 30, in <module>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-10-23 02:29:31,919 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 02:29:31,953 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 02:29:31,953 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 03:34:22,064 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 03:34:22,094 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 03:34:22,094 INFO: Matts brain startup [in /home/mmaitland300/flask/projectmatt/app/__init__.py:104]
2020-10-23 03:34:32,386 ERROR: Exception on /mcshea/mc.html [GET] [in /opt/miniconda3/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/opt/miniconda3/lib/python3.8/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/mmaitland300/flask/projectmatt/app/errors/handlers.py", line 16, in not_found_error
    return render_template('errors/404.html'), 404
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/opt/miniconda3/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/mmaitland300/flask/projectmatt/app/templates/errors/404.html", line 1, in <module>
    {% extends "base.html" %}
  File "/home/mmaitland300/flask/projectmatt/app/templates/base.html", line 1, in <module>
    {% extends 'bootstrap/base.html' %}
  File "/opt/miniconda3/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in <module>
    {% block doc -%}
  File "/opt/miniconda3/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in <module>
    {%- block html %}
  File "/opt/miniconda3/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in <module>
    {% block body -%}
  File "/opt/miniconda3/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in <module>
    {% block navbar %}
  File "/home/mmaitland300/flask/projectmatt/app/templates/base.html", line 56, in <module>
    <li><a href="{{ url_for('static', filename=protect.html) }}">{{ _('Other Stuff') }}</a></li>
  File "/opt/miniconda3/lib/python3.8/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'protect' is undefined
